server:
  servlet:
    session:
      tracking-modes: cookie

spring:
  messages:
    basename: errors

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/datapark
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug

